["母音"]
kanji = "母音"
spelling = ["ぼ", "いん"]
meaning = "Vokal"
score = 10.0

["主語"]
kanji = "主語"
spelling = ["しゅ", "ご"]
meaning = "Subjekt"
score = 10.0

["答え"]
kanji = "答え"
spelling = ["こた"]
meaning = "Antwort"
score = 10.0

["例外"]
kanji = "例外"
spelling = ["れい", "がい"]
meaning = "Ausnahme"
score = 10.0

["単語"]
kanji = "単語"
spelling = ["たん", "ご"]
meaning = "Wort"
score = 10.0

["過去"]
kanji = "過去"
spelling = ["か", "こ"]
meaning = "Vergangenheit"
score = 10.0

["課"]
kanji = "課"
spelling = ["か"]
meaning = "lesson"
score = 10.0

["復習"]
kanji = "復習"
spelling = ["ふく", "しゅう"]
meaning = "Wiederholung"
score = 10.0

["疑問詞"]
kanji = "疑問詞"
spelling = ["ぎ", "もん", "し"]
meaning = "Fragewort"
score = 10.0

["副詞"]
kanji = "副詞"
spelling = ["ふく", "し"]
meaning = "Adverb"
score = 10.0

["動詞"]
kanji = "動詞"
spelling = ["どう", "し"]
meaning = "Verb"
score = 10.0

["形容詞"]
kanji = "形容詞"
spelling = ["けい", "よう", "し"]
meaning = "Adjektiv"
score = 10.0

["目的語"]
kanji = "目的語"
spelling = ["もく", "とき", "ご"]
meaning = "Nomen"
score = 10.0

["助詞"]
kanji = "助詞"
spelling = ["じょ", "し"]
meaning = "Partikel"
score = 10.0

["発音"]
kanji = "発音"
spelling = ["はつ", "おん"]
meaning = "Aussprache"
score = 10.0

["助数詞"]
kanji = "助数詞"
spelling = ["じょ", "すう", "し"]
meaning = "Zähleinheitssuffix"
score = 10.0

["文"]
kanji = "文"
spelling = ["ぶん"]
meaning = "Satz"
score = 10.0

["拍"]
kanji = "拍"
spelling = ["はく"]
meaning = "Mora"
score = 10.0

["読み物"]
kanji = "読み物"
spelling = ["よ", "もの"]
meaning = "Lesetext"
score = 10.0

["子音"]
kanji = "子音"
spelling = ["し", "いん"]
meaning = "Konsonant"
score = 10.0

["活用"]
kanji = "活用"
spelling = ["かつ", "よう"]
meaning = "Flexion"
score = 10.0

["節"]
kanji = "節"
spelling = ["せつ"]
meaning = "Satzglied"
score = 10.0

["練習"]
kanji = "練習"
spelling = ["れん", "しゅう"]
meaning = "Übung"
score = 10.0

["丁寧体"]
kanji = "丁寧体"
spelling = ["てい", "ねい", "たい"]
meaning = "höflicher Stil"
score = 10.0

["述語"]
kanji = "述語"
spelling = ["じゅつ", "ご"]
meaning = "Prädikat"
score = 10.0

["肯定"]
kanji = "肯定"
spelling = ["こう", "てい"]
meaning = "Bejahung"
score = 10.0

["問題"]
kanji = "問題"
spelling = ["もん", "だい"]
meaning = "Aufgabe"
score = 10.0

["否定"]
kanji = "否定"
spelling = ["ひ", "てい"]
meaning = "Verneinung"
score = 10.0

["修飾"]
kanji = "修飾"
spelling = ["しゅう", "しょく"]
meaning = "Bestimmung"
score = 10.0

["名詞"]
kanji = "名詞"
spelling = ["めい", "し"]
meaning = "Nomen"
score = 10.0

["接続詞"]
kanji = "接続詞"
spelling = ["せつ", "ぞく", "し"]
meaning = "Konjunktion"
score = 10.0

["未完了"]
kanji = "未完了"
spelling = ["み", "かん", "りょう"]
meaning = "Imperfekt"
score = 10.0

["普通体"]
kanji = "普通体"
spelling = ["ふ", "つう", "たい"]
meaning = "einfacher Stil"
score = 10.0

["数詞"]
kanji = "数詞"
spelling = ["すう", "し"]
meaning = "Zählwort"
score = 10.0

["文型"]
kanji = "文型"
spelling = ["ぶん", "けい"]
meaning = "Satzmuster"
score = 10.0

["完了"]
kanji = "完了"
spelling = ["かん", "りょう"]
meaning = "Perfekt"
score = 10.0

["非過去"]
kanji = "非過去"
spelling = ["ひ", "か", "こ"]
meaning = "Nichtvergangenheit"
score = 10.0

["句"]
kanji = "句"
spelling = ["く"]
meaning = "Phrase"
score = 10.0

["会話"]
kanji = "会話"
spelling = ["かい", "わ"]
meaning = "Dialog"
score = 10.0

["主題"]
kanji = "主題"
spelling = ["しゅ", "だい"]
meaning = "Thema"
score = 10.0

["索引"]
kanji = "索引"
spelling = ["さく", "いん"]
meaning = "Index"
score = 10.0

["例文"]
kanji = "例文"
spelling = ["れい", "ぶん"]
meaning = "Beispielsatz"
score = 10.0

["文法"]
kanji = "文法"
spelling = ["ぶん", "ぽう"]
meaning = "Grammatik"
score = 10.0

["目次"]
kanji = "目次"
spelling = ["もく", "じ"]
meaning = "Inhaltsverzeichnis"
score = 10.0
